version: '3.4'

services:
  basketdb:
    image: redis:latest
    volumes:
      - redis-data:/path/in/container

  redis-commander:
    image: rediscommander/redis-commander:latest

volumes:
  redis-data:
